### ISSUE TITLE
[PE-D] Recipes are not editable

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-2/tp#204]
If the user makes a typo in making a recipe, he or she will have to delete the whole recipe and retype it again. Which makes it very inconvenient especially if the steps or ingredient list is very long.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: joshualeeky/ped#4

**Comment by dlimyh98** [comment]
Feature already included by @rondayvoo
