### ISSUE TITLE
[PE-D] listRecipes does not print anything when there are no recipes.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-2/tp#206]
When using the function listRecipes, nothing is reported to the user if there is no recipes to be shown. The user is then forced to enter other commands to ensure the program has not crashed, which may be unfriendly to less tech savvy users. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: joshualeeky/ped#5

**Comment by dlimyh98** [comment]
Good point, added a corresponding prompt for this
