### ISSUE TITLE
[PE-D] listRecipe does not work 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-2/tp#213]
![image.png](https://raw.githubusercontent.com/VishalJeyaram/ped/main/files/29c526c1-6985-40af-8c0f-e5a91cfa6553.png)

![image.png](https://raw.githubusercontent.com/VishalJeyaram/ped/main/files/237ca594-ba99-42cb-9091-974b76428ac9.png)

The User guide says to type in "listRecipe" in order to list all possible recipes. However, this doesn't work.

However, when I type in "listRecipes", it works.

![image.png](https://raw.githubusercontent.com/VishalJeyaram/ped/main/files/c62d5304-63c1-46cc-ad0f-a26533e53f16.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: VishalJeyaram/ped#1

**Comment by rondayvoo** [comment]
Similar to issue #202
