### ISSUE TITLE
[PE-D] delete does not work according to the UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-2/tp#218]
![image.png](https://raw.githubusercontent.com/VishalJeyaram/ped/main/files/f6a1ab14-416e-4d29-8a5c-362a376169f1.png)

The example of usage shown in the UG does not actually work, despite having items in my list already.

![image.png](https://raw.githubusercontent.com/VishalJeyaram/ped/main/files/dc17bbfc-3a4d-49cb-a9fe-b93e497bc25c.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: VishalJeyaram/ped#2

**Comment by ChuaXiongWei** [comment]
changed UG to deleteRecipe
