### ISSUE TITLE
[PE-D] find price does not accept dollar sign

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-2/tp#226]
![image.png](https://raw.githubusercontent.com/xuanlc113/ped/main/files/1bf2395a-707b-47f3-83aa-86b7a80f644c.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: xuanlc113/ped#8

**Comment by rondayvoo** [comment]
Working as intended.
