### ISSUE TITLE
[PE-D] time is set for wrong recipe

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-2/tp#234]
![image.png](https://raw.githubusercontent.com/VishalJeyaram/ped/main/files/094392ce-5f27-48b4-b356-2fd3cb32516b.png)
The time was supposed to be set for "peanut butter", but was set for "peanut butter sandwich" instead.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: VishalJeyaram/ped#4

**Comment by dlimyh98** [comment]
Fixed
