### ISSUE TITLE
[PE-D] some commands do not match usage/format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-2/tp#237]
![image.png](https://raw.githubusercontent.com/xuanlc113/ped/main/files/f2729aee-26fa-4d6b-9327-20344f851fca.png)

![image.png](https://raw.githubusercontent.com/xuanlc113/ped/main/files/8b82f60a-3222-482f-ac09-366328794815.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: xuanlc113/ped#11

**Comment by rondayvoo** [comment]
Mentioned in #202 and #209
