### ISSUE TITLE
[PE-D] addRecipe command accepts blank description for anything

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-2/tp#241]
Same problem as the steps part of your addRecipe command. It seems I can write blank spaces or special characters and the program will still accept the inputs for recipe_name, ingredients or steps. In other words, I can add a recipe that has no information.

![Screenshot (145).png](https://raw.githubusercontent.com/Nirmaleshwar/ped/main/files/281abe02-8298-42f3-8cff-2196696922b7.png)

This is quite a major issue but you can simply fix it by accounting for blank inputs.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Nirmaleshwar/ped#5

**Comment by dlimyh98** [comment]
related to #205 

1. special characters will still be allowed
2. recipeName, ingredients, steps will now enforce that ANY field cannot be blank
