### ISSUE TITLE
[PE-D] Price is not set properly 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-2/tp#242]
![image.png](https://raw.githubusercontent.com/VishalJeyaram/ped/main/files/0985ddf1-aa7b-47be-a288-95682fd32a4d.png)

Desired price is being set to the wrong recipe.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: VishalJeyaram/ped#7

**Comment by dlimyh98** [comment]
related to #198
