### ISSUE TITLE
[PE-D] Finding tag command is does not match help guide 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-2/tp#246]
![image.png](https://raw.githubusercontent.com/VishalJeyaram/ped/main/files/8636a396-d110-4290-902f-3fd7e33c0f87.png)

![image.png](https://raw.githubusercontent.com/VishalJeyaram/ped/main/files/79c1d22f-cf1c-429a-99bd-d771ae5ebaab.png)

The help guide states to use "/tags" as the keyword when searching for a recipe with the tag name you wish to find. However, it doesn't work. "tag" only works properly. 

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: VishalJeyaram/ped#8

**Comment by dlimyh98** [comment]
Fixed.
